baseURL: /
title: Tekton
enableRobotsTXT: true
theme:
  - github.com/imfing/hextra
enableGitInfo: true
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
disableKinds:
  - taxonomy
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: manni
enableEmoji: true
ignoreFiles:
  - vendor/.*
rss_sections:
  - blog
permalinks:
  blog: /:section/:year/:month/:day/:slug/
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
services:
  googleAnalytics:
    id: G-G2WH79BEEM
languages:
  en:
    title: Tekton
    languageName: English
    weight: 1
    params:
      description: Cloud Native CI/CD

params:
  description: Cloud Native CI/CD
  github_repo: https://github.com/tektoncd/website

  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      dark: images/logo-dark.svg
      light: images/logo.svg
      link: /
      width: 28
      height: 28

  search:
    enable: true
    type: flexsearch
    flexsearch:
      index: content

  editURL:
    enable: true
    base: https://github.com/tektoncd/website/edit/main/content

  footer:
    displayPoweredBy: false

  theme:
    default: system
    displayToggle: true

  page:
    width: wide

  links:
    developer:
      - name: Slack
        url: https://join.slack.com/t/tektoncd/shared_invite/zt-1z8ctzsyv-wLXWwA2Rl3AOhcNGqpWRUw
        icon: fab fa-slack
        desc: Slack Channel for Tekton Project
      - name: GitHub
        url: https://github.com/tektoncd
        icon: fab fa-github
        desc: GitHub organization for the Tekton project

menu:
  main:
    - identifier: Documentation
      name: Documentation
      pageRef: /docs
      weight: 1
    - identifier: Blog
      name: Blog
      pageRef: /blog
      weight: 2
    - identifier: Community
      name: Community
      pageRef: /community
      weight: 3
    - identifier: GitHub
      name: GitHub
      url: https://github.com/tektoncd
      weight: 4
      params:
        icon: github
